blog:
  avatar: https://avatars.githubusercontent.com/u/195545824?v=4
  name: 𝐀𝐞𝟏𝐚𝐮𝐭𝐮𝐦𝐧
  sname: 特别项目
  description: 𝔸 ℍ𝕚𝕟𝕥 𝕠𝕗 𝔹𝕚𝕥𝕥𝕖𝕣𝕟𝕖𝕤𝕤, 𝕒 𝕎𝕚𝕤𝕡 𝕠𝕗 𝕊𝕨𝕖𝕖𝕥𝕟𝕖𝕤𝕤, 𝕒 𝕋𝕠𝕦𝕔𝕙 𝕠𝕗 𝕋𝕒𝕣𝕥𝕟𝕖𝕤𝕤
  favicon: https://avatars.githubusercontent.com/u/195545824?v=4
  theme:
    mode: dark
    primary_color: '#e74c3c'
    dark_bg: '#121212'
    light_bg: '#f5f7fa'
articles:
- id: c1
  title: c1
  date: '2026-04-22'
  tags: []
  content: 暂无简介
  url: article/c1.html
  verticalTitle: c1
- id: SKILL
  title: SKILL
  date: '2026-04-22'
  tags: []
  content: 暂无简介
  url: article/SKILL.html
  verticalTitle: SKILL
- id: gem
  title: gem
  date: '2026-04-22'
  tags: []
  content: 暂无简介
  url: article/gem.html
  verticalTitle: gem
- id: '21'
  title: '04.05'
  date: '2026-04-05'
  tags:
  - 记录
  content: 暂无简介
  url: article/21.html
  verticalTitle: '04.05'
- id: '19'
  title: '03.27'
  date: '2026-03-27'
  tags:
  - 记录
  content: 暂无简介
  url: article/19.html
  verticalTitle: '03.27'
- id: '18'
  title: '"我"'
  date: '2026-02-24'
  tags:
  - 记录
  - 回忆
  content: 暂无简介
  url: article/18.html
  verticalTitle: '"我"'
- id: '17'
  title: Gem-3
  date: '2026-02-15'
  tags:
  - 记录
  - 普通
  content: 暂无简介
  url: article/17.html
  verticalTitle: Gem-3
- id: '16'
  title: Gem-2
  date: '2026-02-15'
  tags:
  - 记录
  - 普通
  content: 暂无简介
  url: article/16.html
  verticalTitle: Gem-2
- id: '15'
  title: Gem-1
  date: '2026-02-15'
  tags:
  - 记录
  - 普通
  content: 暂无简介
  url: article/15.html
  verticalTitle: Gem-1
- id: '14'
  title: '02.02'
  date: '2026-02-02'
  tags:
  - 记录
  - 普通
  content: 暂无简介
  url: article/14.html
  verticalTitle: '02.02'
- id: '13'
  title: SDB
  date: '2026-01-31'
  tags:
  - 普通
  content: 暂无简介
  url: article/13.html
  verticalTitle: SDB
- id: '11'
  title: '01.29'
  date: '2026-01-29'
  tags:
  - 记录
  - 普通
  content: 暂无简介
  url: article/11.html
  verticalTitle: '01.29'
specials:
- id: '12'
  title: SB
  date: '2026-01-31'
  tags:
  - special
  content: 暂无简介
  url: article/12.html
  verticalTitle: SB
floating_menu:
- tag: about
  display: 关于
special_config:
  top: true
  view:
    RF_Information: ''
    RF_Link: ''
    Copyright: ''
    C_Link: ''
    Total_time: 2026.01.01
    Others: ''
