blog:
  avatar: https://avatars.githubusercontent.com/u/195545824?v=4
  name: Ae1autumn
  sname: 特别项目
  description: I was only temporary to you
  favicon: https://avatars.githubusercontent.com/u/195545824?v=4
  theme:
    mode: dark
    primary_color: '#e74c3c'
    dark_bg: '#121212'
    light_bg: '#f5f7fa'
articles:
- id: '4'
  title: yyh
  date: '2026-01-05'
  tags: []
  content:
  - 暂无简介
  url: article/4.html
  verticalTitle: yyh
- id: '3'
  title: Tek It
  date: '2026-01-05'
  tags:
  - 普通
  content:
  - 暂无简介
  url: article/3.html
  verticalTitle: Tek It
specials:
- id: '2'
  title: R_Land
  date: '2026-01-04'
  tags:
  - top
  content:
  - 暂无简介
  url: article/2.html
  verticalTitle: R_Land
floating_menu:
- tag: about
  display: 关于
special_config:
  top: true
  view:
    RF_Information: ''
    RF_Link: ''
    Copyright: ''
    C_Link: ''
    Total_time: 2026.01.01
    Others: ''
