blog:
  avatar: "https://avatars.githubusercontent.com/u/195545824?v=4"
  name: "𝐀𝐞𝟏𝐚𝐮𝐭𝐮𝐦𝐧"
  sname: "特别项目"
  description: "𝔸 ℍ𝕚𝕟𝕥 𝕠𝕗 𝔹𝕚𝕥𝕥𝕖𝕣𝕟𝕖𝕤𝕤, 𝕒 𝕎𝕚𝕤𝕡 𝕠𝕗 𝕊𝕨𝕖𝕖𝕥𝕟𝕖𝕤𝕤, 𝕒 𝕋𝕠𝕦𝕔𝕙 𝕠𝕗 𝕋𝕒𝕣𝕥𝕟𝕖𝕤𝕤"
  favicon: "https://avatars.githubusercontent.com/u/195545824?v=4"

  theme:
    mode: "dark"
    primary_color: "#e74c3c"
    dark_bg: "#121212"
    light_bg: "#f5f7fa"

floating_menu:
  - tag: "about"
    display: "关于"

special:
  top: true
  view:
    RF_Information: ""
    RF_Link: ""
    Copyright: ""
    C_Link: ""
    Total_time: "2026.01.01"
    Others: ""

templates:
  article: "article.html"
  home: "home.html"

special_tags:
  - "top"
  - "special"
  - "项目"
